Source Code/BabyShopping/Controllers/AboutController.cs
using System.Web.Mvc;
using BabyShop.BusinessLayer.Manager;

namespace BabyShopping.Controllers
{
    public class AboutController : BaseController
    {
        //
        // GET: /About/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OurStandards()
        {
            ProductCartManager productCartMgr = new ProductCartManager();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());
            return View();
        }

        public ActionResult Claudia()
        {
            ProductCartManager productCartMgr = new ProductCartManager();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());
            return View();
        }
    }
}

Source Code/BabyShopping/Controllers/FAQController.cs
using System.Web.Mvc;
using BabyShop.BusinessLayer.Manager;

namespace BabyShopping.Controllers
{
    public class FAQController : BaseController
    {
        //
        // GET: /FAQ/
        public ActionResult Index()
        {
            ProductCartManager productCartMgr = new ProductCartManager();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());
            return View();
        }
    }
}

Source Code/BabyShopping/Controllers/FooterController.cs
using System.Web.Mvc;
using BabyShop.BusinessLayer.Manager;

namespace BabyShopping.Controllers
{
    public class FooterController : BaseController
    {
        //
        // GET: /Footer/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PrivacyPolicy()
        {
            ProductCartManager productCartMgr = new ProductCartManager();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());
            return View();
        }

        public ActionResult TermsAndConditions()
        {
            ProductCartManager productCartMgr = new ProductCartManager();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());
            return View();
        }
    }
}

Source Code/BabyShopping/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BabyShop.BusinessLayer.Manager;
using BabyShop.Models;

namespace BabyShopping.Controllers
{
    public class ProductController : BaseController
    {
        public ActionResult Index(ProductModel product)
        {
            var productCartMgr = new ProductCartManager();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());
            ViewBag.ProductId = product.Id;
            ViewBag.Price = product.Price;
            ViewBag.ProductName = product.Name;
            ViewBag.Description = product.Description;
            var productManager = new ProductManager();
            var productImages = productManager.GetProductImagesById(product.Id);
            return View("ProductDetail", productImages);

        }
        public ActionResult Product()
        {
            var productCartMgr = new ProductCartManager();
            var productManager = new ProductManager();

            IList<ProductModel> productModels = productManager.GetallProducts();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());

            return View(productModels);
        }

    }
}

Source Code/BabyShopping/Views/Shared/_Inner.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/Common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/flexdropdown.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/Styles/Class.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jquery.jqzoom.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        sessionStorage.cartItemCount = "@ViewBag.ItemsCount" == " " ? 0 : "@ViewBag.ItemsCount";
    </script>
    @RenderSection("Head", false)
</head>
<body onload="javascript:return LoadCartItems();">
    <div id="wraper">
        <div id="header" class="Header">
            <div id="title">
            </div>
            <ul id="flexmenu1" class="flexdropdownmenu">
                <div class="flexdropTopMenu">
                    <img src="@Url.Content("~/Content/Images/droptop.png")" alt="" />
                </div>
                <li>@Html.ActionLink("Our Standards", "OurStandards", "About")</li>
                <li>@Html.ActionLink("Claudia", "Claudia", "About")</li>
                <div>
                    <img src="@Url.Content("~/Content/Images/dropBot.png")" alt="" />
                </div>
            </ul>
            <div class="main-container">
                <div class="logo fl">
                    <a href="@Url.Content("~/Home/Index")">
                        <img src="@Url.Content("~/Content/Images/logo.gif")" alt="" />
                    </a>
                </div>
                <div class="nav fl">
                    <ul id="menu">
                        <li>@Html.ActionLink("Shop", "Product", "Product")</li>
                        <li><a href="#" data-flexmenu="flexmenu1">About Us</a></li>
                        <li>@Html.ActionLink("Safe Sleep Guidelines", "Index", "Home")</li>
                        <li>@Html.ActionLink("F.A.Q", "Index", "FAQ")</li>
                    </ul>
                </div>
                <div class="fr searchContainer">
                    <div class="fl search">
                        <input type="text" value="" />
                        <input type="submit" value="" class="btn" />
                    </div>
                    <div class="fl addCart">
                        <label id="lblCartItems">
                        </label>
                        <br />
                        <a onclick="javascript:fnAddtoCart();">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" /></a></div>
                    <div class="cl">
                    </div>
                </div>
                <div class="cl">
                </div>
            </div>
        </div>
        <div class="inner-section">
            <div class="container">
                <div class="inner-section">
                    <div class="roundedTop">
                        <img src="../../Content/Images/roundtopLft.png" alt="" class="fl" />
                        <img src="../../Content/Images/roundtopRght.png" alt="" class="fr" />
                    </div>
                    <div class="roundedBg">
                        @RenderBody()
                    </div>
                    <div class="roundedBot">
                        <img src="@Url.Content("~/Content/Images/roundbotLft.png")" alt="" class="fl" />
                        <img src="@Url.Content("~/Content/Images/roundbotRght.png")" alt="" class="fr" />
                    </div>
                    <div class="cl">
                    </div>
                </div>
            </div>
        </div>
        <div class="cl">
        </div>
        <div class="footer">
            <div class="main-container">
                <div class="fl footerLinks">
                    <ul>
                        <li>@Html.ActionLink("terms & conditions", "TermsAndConditions", "Footer")</li>
                        <li>@Html.ActionLink("privacy policy", "PrivacyPolicy", "Footer")</li>
                        <li><a href="#">refund policy</a></li>
                        <li><a href="#">site map</a></li>
                        <li><a href="#">contact us</a></li>
                        <li><a href="#">blog</a></li>
                        <li><a href="#">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="twitter" /></a><a
                                href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="facebook" /></a><a
                                    href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="thirdicon" /></a></li>
                        <div class="cl">
                        </div>
                    </ul>
                </div>
                <div class="fl padT10">
                    &copy; 2013 Hush Pure Sleep</div>
                <div class="fr padT10">
                    Powered By MaduTech Pvt. Ltd.</div>
            </div>
        </div>
        <div class="cl">
        </div>
    </div>
</body>
</html>

Source Code/BabyShopping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/Common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/flexdropdown.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/Styles/Class.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/1.5.1-jquery.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/slides.min.jquery.js")"></script>
    <script type="text/javascript" language="javascript">
        $(function () {
            // Set starting slide to 1
            var startSlide = 1;
            // Get slide number if it exists
            if (window.location.hash) {
                startSlide = window.location.hash.replace('#', '');
            }
            // Initialize Slides
            $('#slides').slides({
                preload: true,
                preloadImage: 'images/loading.gif',
                generatePagination: true,
                play: 5000,
                pause: 2500,
                hoverPause: false,
                // Get the starting slide
                start: startSlide,
                animationComplete: function (current) {
                    // Set the slide number as a hash
                    // window.location.hash = '#' + current;
                }
            });
        });
    </script>
    <style type="text/css">
        .TB_Wrapper
        {
            width: 100%;
            height: 768px;
        }
    </style>
    <link rel="stylesheet" href="@Url.Content("~/Content/trans_banner/style.css")" />
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Content/trans_banner/jquery.easing.1.3.min.js")"></script>
    <script type="text/javascript" language="javascript" src="@Url.Content("~/Content/trans_banner/trans-banner.min.js")"></script>
    <script type="text/javascript">
        jQuery(function ($) {
            $('.TB_Wrapper').TransBanner({
                button_show_back: true,
                button_numbers_horizontal: true,
                caption_float_mode: true,
                caption_bg_blur: 0,
                caption_bg_color: '#000000',
                caption_bg_opacity: .7,
                caption_bg_radius: 4,
                caption_bg_shadow: 0,
                caption_border: 0,

                /*All the below settings are related to responsive behavior:
                IMPORTANT: In order to make limits to work on browser resize, set the last parameter to false	
                
                To enable or disable Responsive behavior */
                responsive: true,

                /* To disable autoplay below certain screen size [Ex: 480] */
                responsive_limit_autoplay: '',

                /* To disable caption below certain screen size [Ex: 480]*/
                responsive_limit_caption: 480,

                /* To change navigation type below certain screen size [Ex: 480]*/
                responsive_limit_navigation: 480,

                /* The navigation type to be used below certain screen size [1: Default, 2: Dot style, 3: Arrow style]*/
                responsive_limit_navigation_type: 2,

                /* The limits can be either screen based or banner container based */
                responsive_screen_based_limits: true
            });
        });

        sessionStorage.cartItemCount = "@ViewBag.ItemsCount" == " " ? 0 : "@ViewBag.ItemsCount";
    </script>
</head>
<body onload="javascript:return LoadCartItems();">
    <div id="wraper">
        <div id="header" class="Header">
            <div id="title">
            </div>
            @*<div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>*@
            <ul id="flexmenu1" class="flexdropdownmenu">
                <div class="flexdropTopMenu">
                    <img src="@Url.Content("~/Content/Images/droptop.png")" alt="" />
                </div>
                <li>@Html.ActionLink("Our Standards", "OurStandards", "About")</li>
                <li>@Html.ActionLink("Claudia", "Claudia", "About")</li>
                <div>
                    <img src="@Url.Content("~/Content/Images/dropBot.png")" alt="" />
                </div>
            </ul>
            <div class="main-container">
                <div class="logo fl">
                    <a href="../Home/Index">
                        <img src="@Url.Content("~/Content/Images/logo.gif")" alt="" />
                    </a>
                </div>
                <div class="nav fl">
                    <ul id="menu">
                        <li>@Html.ActionLink("Shop", "Product", "Product")</li>
                        <li><a href="#" data-flexmenu="flexmenu1">About Us</a></li>
                        <li>@Html.ActionLink("Safe Sleep Guidelines", "Index", "Home")</li>
                        <li>@Html.ActionLink("F.A.Q", "Index", "FAQ")</li>
                    </ul>
                </div>
                <div class="fr searchContainer">
                    <div class="fl search">
                        <input type="text" value="" />
                        <input type="submit" value="" class="btn" />
                    </div>
                    <div class="fl addCart">
                        <label id="lblCartItems">
                        </label>
                        <br />
                        <a onclick="javascript:fnAddtoCart();">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" /></a></div>
                    <div class="cl">
                    </div>
                </div>
                <div class="cl">
                </div>
            </div>
        </div>
        <div class="TB_Wrapper">
            <div class="Slides">
                <div class="Slide" data-caption_bg_color="#FF0000" data-caption_bg_opacity="0.5">
                    <img src="@Url.Content("~/Content/Images/Baby1.gif")" alt="img1" width="1200" height ="768" />
                </div>
                <div class="Slide" data-position="50,80" data-caption_bg_color="#FF0000" data-caption_bg_opacity="0.5">
                    <img src="@Url.Content("~/Content/Images/Baby2.gif")" alt="img1" width="1200" height ="768" />
                </div>
                <div class="Slide" data-position="50,80" data-caption_bg_color="#FF0000" data-caption_bg_opacity="0.5">
                    <img src="@Url.Content("~/Content/Images/Baby3.gif")" alt="img1" width="1200" height ="768" />
                </div>
            </div>
            <div class="main-section-midd">
                <div class="main-container middhomesection">
                    @RenderBody()
                    <div class="slogen">
                        Soft sleep product for babies</div>
                </div>
            </div>
        </div>
        <div class="cl">
        </div>
        <div class="footer">
            <div class="main-container">
                <div class="fl footerLinks">
                    <ul>
                        <li>@Html.ActionLink("terms & conditions", "TermsAndConditions", "Footer")</li>
                        <li>@Html.ActionLink("privacy policy", "PrivacyPolicy", "Footer")</li>
                        <li><a href="#">refund policy</a></li>
                        <li><a href="#">site map</a></li>
                        <li><a href="#">contact us</a></li>
                        <li><a href="#">blog</a></li>
                        <li><a href="#">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="twitter" /></a><a
                                href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="facebook" /></a><a
                                    href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="thirdicon" /></a></li>
                    </ul>
                </div>
                <div class="fr padT10">
                    &copy; 2013 Hush Pure Sleep</div>
                <div class="fr padT10">
                    Powered By MaduTech Pvt. Ltd.</div>
            </div>
        </div>
        <div class="cl">
        </div>
    </div>
</body>
</html>

Source Code/BabyShopping/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

Source Code/BabyShopping/Views/Shared/_PaymentMaster.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/flexdropdown.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/Common.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/Styles/Class.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="wraper">
        <div id="header" class="Header">
            <div id="title">
            </div>
            @*<div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>*@
            <ul id="flexmenu1" class="flexdropdownmenu">
                <div class="flexdropTopMenu">
                    <img src="@Url.Content("~/Content/Images/droptop.png")" alt="" />
                </div>
                <li>@Html.ActionLink("Our Standards", "OurStandards", "About")</li>
                <li>@Html.ActionLink("Claudia", "Claudia", "About")</li>
                <div>
                    <img src="@Url.Content("~/Content/Images/dropBot.png")" alt="" />
                </div>
            </ul>
            <div class="main-container">
                <div class="logo fl">
                    <a href="../Home/Index">
                        <img src="@Url.Content("~/Content/Images/logo.gif")" alt="" />
                    </a>
                </div>
                <div class="nav fl">
                    <ul id="menu">
                        <li>@Html.ActionLink("Shop", "Product", "Product")</li>
                        <li><a href="#" data-flexmenu="flexmenu1">About Us</a></li>
                        <li>@Html.ActionLink("Safe Sleep Guidelines", "Index", "Home")</li>
                        <li>@Html.ActionLink("F.A.Q", "Index", "FAQ")</li>
                    </ul>
                </div>
                <div class="fr searchContainer">
                    <div class="fl search">
                        <input type="text" value="" />
                        <input type="submit" value="" class="btn" />
                    </div>
                    <div class="fl addCart">
                        <label id="lblCartItems">
                        </label>
                        <br />
                        <a href="#" onclick="javascript:fnAddtoCart();">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" /></a></div>
                    <div class="cl">
                    </div>
                </div>
                <div class="cl">
                </div>
            </div>
        </div>
        <div class="inner-section">
            <div class="container">
                @RenderBody()
            </div>
        </div>
        <div class="cl">
        </div>
        <div class="footer">
            <div class="main-container">
                <div class="fl footerLinks">
                    <ul>
                        <li><a href="#">terms &amp; conditions</a></li>
                        <li><a href="#">privacy policy</a></li>
                        <li><a href="#">refund policy</a></li>
                        <li><a href="#">site map</a></li>
                        <li><a href="#">contact us</a></li>
                        <li><a href="#">blog</a></li>
                        <li><a href="#">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="twitter" /></a><a
                                href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="facebook" /></a><a
                                    href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="thirdicon" /></a></li>
                        <div class="cl">
                        </div>
                    </ul>
                </div>
                <div class="fr padT10">
                    &copy; 2011 Hush Pure Sleep</div>
            </div>
        </div>
        <div class="cl">
        </div>
    </div>
</body>
</html>

Source Code/BabyShopping/Views/Shared/_Product.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/Common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Scripts/flexdropdown.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/Styles/Class.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jquery.jqzoom.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        sessionStorage.cartItemCount = "@ViewBag.ItemsCount" == " " ? 0 : "@ViewBag.ItemsCount";
    </script>
    @RenderSection("Head", false)
</head>
<body onload="javascript:return LoadCartItems();">
    <div id="wraper">
        <div id="header" class="Header">
            <div id="title">
            </div>
            <ul id="flexmenu1" class="flexdropdownmenu">
                <div class="flexdropTopMenu">
                    <img src="@Url.Content("~/Content/Images/droptop.png")" alt="" />
                </div>
                <li>@Html.ActionLink("Our Standards", "OurStandards", "About")</li>
                <li>@Html.ActionLink("Claudia", "Claudia", "About")</li>
                <div>
                    <img src="@Url.Content("~/Content/Images/dropBot.png")" alt="" />
                </div>
            </ul>
            <div class="main-container">
                <div class="logo fl">
                    <a href="@Url.Content("~/Home/Index")">
                        <img src="@Url.Content("~/Content/Images/logo.gif")" alt="" />
                    </a>
                </div>
                <div class="nav fl">
                    <ul id="menu">
                        <li>@Html.ActionLink("Shop", "Product", "Product")</li>
                        <li><a href="#" data-flexmenu="flexmenu1">About Us</a></li>
                        <li>@Html.ActionLink("Safe Sleep Guidelines", "Index", "Home")</li>
                        <li>@Html.ActionLink("F.A.Q", "Index", "FAQ")</li>
                    </ul>
                </div>
                <div class="fr searchContainer">
                    <div class="fl search">
                        <input type="text" value="" />
                        <input type="submit" value="" class="btn" />
                    </div>
                    <div class="fl addCart">
                        <label id="lblCartItems">
                        </label>
                        <br />
                        <a onclick="javascript:fnAddtoCart();">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" /></a></div>
                    <div class="cl">
                    </div>
                </div>
                <div class="cl">
                </div>
            </div>
        </div>
        <div class="inner-section">
            <div class="container">
                @RenderBody()
            </div>
        </div>
        <div class="cl">
        </div>
        <div class="footer">
            <div class="main-container">
                <div class="fl footerLinks">
                    <ul>
                        <li>@Html.ActionLink("terms & conditions", "TermsAndConditions", "Footer")</li>
                        <li>@Html.ActionLink("privacy policy", "PrivacyPolicy", "Footer")</li>
                        <li><a href="#">refund policy</a></li>
                        <li><a href="#">site map</a></li>
                        <li><a href="#">contact us</a></li>
                        <li><a href="#">blog</a></li>
                        <li><a href="#">
                            <img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="twitter" /></a><a
                                href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="facebook" /></a><a
                                    href="#"><img src="@Url.Content("~/Content/Images/spacer.gif")" alt="" class="thirdicon" /></a></li>
                        <div class="cl">
                        </div>
                    </ul>
                </div>
                <div class="fl padT10">
                    &copy; 2013 Hush Pure Sleep</div>
                <div class="fr padT10">
                    Powered By MaduTech Pvt. Ltd.</div>
            </div>
        </div>
        <div class="cl">
        </div>
    </div>
</body>
</html>