Source Code/BabyShopping/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BabyShop.BusinessLayer.Manager;
using BabyShop.Models;

namespace BabyShopping.Controllers
{
    public class ProductController : BaseController
    {
        public ActionResult Index(ProductModel product)
        {
            var productCartMgr = new ProductCartManager();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());
            ViewBag.ProductId = product.Id;
            ViewBag.Price = product.Price;
            ViewBag.ProductName = product.Name;
            ViewBag.Description = product.Description;
            var productManager = new ProductManager();
            var productImages = productManager.GetProductImagesById(product.Id);
            return View("ProductDetail", productImages);

        }
        public ActionResult Product()
        {
            var productCartMgr = new ProductCartManager();
            var productManager = new ProductManager();

            IList<ProductModel> productModels = productManager.GetallProducts();
            ViewBag.ItemsCount = productCartMgr.CountCartItems(GetShoppingCartId());

            return View(productModels);
        }

    }
}

Source Code/BabyShopping/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BabyShop.BusinessLayer.Manager;
using BabyShop.Models;

namespace BabyShopping.Controllers
{
    public class ShopController : BaseController
    {
        private Guid shoppingCartId;
        readonly ProductCartManager productCartManager = new ProductCartManager();
        //
        // GET: /Shop/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShoppingCart(ProductCartModel productCart)
        {
            IList<ProductCartModel> productCartModelList;

            shoppingCartId = base.GetShoppingCartId();

            if (productCart.ProductId > 0)
            {
                productCartModelList = productCartManager.GetCartItems(shoppingCartId);
                ProductCartModel productCartModel = productCartModelList.FirstOrDefault(x => x.ProductId == productCart.ProductId);
                if (productCartModel == null)
                {
                    productCart.CartId = shoppingCartId;
                    bool status = productCartManager.InsertProductCart(productCart);
                }
            }

            productCartModelList = productCartManager.GetCartItems(shoppingCartId);
            ViewBag.ItemsCount = productCartManager.CountCartItems(shoppingCartId);

            return View(productCartModelList);
        }

        [HttpPost]
        public ActionResult PopulateGrid()
        {
            shoppingCartId = base.GetShoppingCartId();
            return RedirectToAction("ShoppingCart", productCartManager.GetCartItems(shoppingCartId).FirstOrDefault());
        }

        public ActionResult DeleteItemInShoppingCart(int productCartId)
        {
            shoppingCartId = base.GetShoppingCartId();

            var productCartManager = new ProductCartManager();
            this.productCartManager.DeleteShoppingCart(productCartId);
            ViewBag.ItemsCount = productCartManager.CountCartItems(shoppingCartId);

            return View("ShoppingCart", productCartManager.GetCartItems(shoppingCartId));
        }

        [HttpPost]
        public ActionResult UpdateQuantityInCart(int productCartId, int quantity)
        {
            shoppingCartId = base.GetShoppingCartId();

            var productCartModel = new ProductCartModel();
            productCartModel.Id = productCartId;
            productCartModel.Quantity = quantity;

            var productCartManager = new ProductCartManager();
            productCartManager.UpdateQuantityInCart(productCartModel);
            return RedirectToAction("ShoppingCart", productCartManager.GetCartItems(shoppingCartId).FirstOrDefault());
        }

        public ActionResult TermCondition()
        {
            return View();
        }

        public ActionResult CheckOut()
        {
            UserManager userMgr = new UserManager();
            UserModel userModel = userMgr.GetUserDetails(GetLoggedInUserId());
            return View(userModel);
        }

        public ActionResult ChangeAddress()
        {
            return View();
        }
    }
}

Source Code/BabyShopping/Views/Product/Product.cshtml
@model IEnumerable<BabyShop.Models.ProductModel>

@{
    ViewBag.Title = "BabyProduct";
    Layout = "~/Views/Shared/_Product.cshtml";
}
<div class="inner-section">
    @{
        int counter = 0;
        decimal remainder = 0;
        string imagePath = System.Web.Configuration.WebConfigurationManager.AppSettings["ImageFolder"];
    }
    @foreach (var product in Model)
    {
        counter = counter + 1;
        remainder = counter % 3;
       
        <div class="shadowBoxSmal fl">
            <div class="shadowTopSmal">
                &nbsp;</div>
            <form id="Form1" action="@Url.Action("Index", "Product", product)" method="post">
            <div class="shadowContSmal">
                <img src="@Url.Content(imagePath + @product.ImageURL)" width="100%" alt="" />
                <h4 class="blueColr">
                    <label id="lblStrippedOne">
                        @product.Name</label></h4>
                @product.Description
                <p>
                    <label id="lblPriceOne">
                        $@product.Price</label></p>
                <p>
                    <input type="submit" value="" class="productDetail" />
                </p>
            </div>
            </form>
            <div class="shadowBotSmal">
                &nbsp;</div>
        </div>
        if (remainder == 0)
        {
        <br />
        }
    }
    <div class="cl">
    </div>
</div>

Source Code/BabyShopping/Views/Product/ProductDetail.cshtml
@model IEnumerable<BabyShop.Models.ProductImagesModel>
@{
    ViewBag.Title = "ProductDetail";
    Layout = "~/Views/Shared/_Product.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#imageZoom').attr('href', jsnUtil.imageZoomDir + '@Model.First().ZoomImageURL');
        $('#imagePropduct').attr('src', jsnUtil.imageDir + '@Model.First().MidImageURL');
    });
</script>
<script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/Scripts/ProductDetail.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.jqzoom-core.js")" type="text/javascript"></script>
<div class="inner-section">
    <div class="shadowBox fl">
        <div class="shadowTop">
            &nbsp;</div>
        <div class="shadowCont">
            <div class="clearfix">
                <a id="imageZoom" href="" class="MyCLASS" rel='gal1' title="">
                    <img id="imagePropduct" src="" title="" alt="" />
                </a>
            </div>
            <div class="cl">
            </div>
            <div class="rollthumb clearfix">
                <p class="rollTxt">
                    Roll over image to zoom in
                </p>
                <ul id="thumblist" class="clearfix">
                    @{bool flag = true;}
                    @foreach (var productImage in Model)
                    {
                        if (flag)
                        {
                        <li><a class="zoomThumbActive" href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '@Url.Content("~/Content/Images/" + productImage.MidImageURL)',
                            largeimage: '@Url.Content("~/Content/Zoom/" + productImage.ZoomImageURL)'}">
                            <img src='@Url.Content("~/Content/Images/" + productImage.SmallImageURL)' alt="rollingThumb1"/>
                        </a></li>
                            flag = false;
                        }
                        else
                        {
                        <li><a  href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '@Url.Content("~/Content/Images/" + productImage.MidImageURL)',
                            largeimage: '@Url.Content("~/Content/Zoom/" + productImage.ZoomImageURL)'}">
                            <img src='@Url.Content("~/Content/Images/" + productImage.SmallImageURL)' alt="rollingThumb1"/>
                        </a></li>
                            
                        }

                    }
                </ul>
                <div class="cl">
                </div>
            </div>
        </div>
        <div class="shadowBot">
            &nbsp;</div>
    </div>
    <div class="shadowBox fr">
        <div class="shadowTop">
            &nbsp;</div>
        <div class="shadowCont">
            <div class="detailCont">
                <h3>
                    @ViewBag.ProductName</h3>
                <div class="cartRow">
                    <div class="price fl">
                        <b>Details</b></div>
                    <div class="price blueColr fl">
                        <b>Fabric &amp; Care</b></div>
                    <div class="price blueColr fl">
                        <b>Shipping</b></div>
                    <div class="cl">
                    </div>
                </div>
                <p>
                    @ViewBag.Description
                </p>
            </div>
            <div class="detailCont">
                <div class="cartRow">
                    <b>Ordering</b>
                </div>
                <br />
                <form action="@Url.Action("ShoppingCart", "Shop")" method="post" class="formCont">
                <input id="hdnProductId" name = "ProductId" type="hidden" value="@ViewBag.ProductId" />
                <div class="formRow">
                    <label>
                        Size</label>&nbsp;&nbsp;
                    <select name="">
                        <option>Choose an Option</option>
                    </select>
                    <div class="cl">
                    </div>
                </div>
                <br />
                <div class="formRow">
                    <label>
                        Color</label>
                    <select name="">
                        <option selected="selected">Choose an Option</option>
                    </select>
                    <div class="cl">
                    </div>
                </div>
                <br />
                <div class="formRow">
                    <label>
                        Price</label>
                    $@ViewBag.Price
                    <div class="cl">
                    </div>
                </div>
                <div class="formRow">
                    <label>
                        Quantity</label>
                    <input name="Quantity" id="Quantity" type="text" value="1" style="width: 50px;" />
                    <input type="submit" value="" class="addToCart" id="btnAddToCart" />
                    <div class="cl">
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="shadowBot">
            &nbsp;</div>
    </div>
    <div class="cl">
    </div>
</div>